Repository filipedeschamps/tabnews.com.br, pull requests merged in 2023-12, with the labels that each got.

#1188 Feature (API) - Adiciona query params para filtrar lista de conteúdos do usuário
  models/content.js
  models/validator.js
  pages/api/v1/contents/[username]/index.public.js
  tests/integration/api/v1/contents/[username]/get.test.js
Labels: back

#1573 [Responsividade e Acessibilidade] Truncar `username` longo na lista de conteúdos e mais
  pages/interface/components/ContentList/index.js
  pages/interface/components/Header/index.js
  pages/interface/components/PastTime/index.js
  pages/interface/components/TabCashCount/index.js
  pages/interface/components/TabCoinCount/index.js
  pages/interface/components/ThemeSelector/index.js
Labels: front, acessibilidade, responsividade

#1574 Criação de templates de issue e pull request
  .github/ISSUE_TEMPLATE/1_bug_report.yml
  .github/ISSUE_TEMPLATE/2_feature_request.yml
  .github/ISSUE_TEMPLATE/3_question.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/pull_request_template.md
Labels: documentação

#1584 Salvar Email no autocomplete ao invés do Nome de Usuário no Cadastro
  pages/cadastro/index.public.js
Labels: front, bug

#1577 Filtro de conteúdos na página do usuário
  pages/[username]/comentarios/[page]/index.public.js
  pages/[username]/conteudos/[page]/index.public.js
  pages/[username]/index.public.js
  pages/interface/components/EmptyState/index.js
  pages/interface/components/Header/index.js
  pages/interface/components/Link/index.js
  pages/interface/components/TabCashCount/index.js
  pages/interface/components/TabCoinCount/index.js
  pages/interface/components/TabNewsUI/index.js
  pages/interface/components/UserHeader/index.js
Labels: front, novo recurso
