Repository filipedeschamps/tabnews.com.br, pull requests merged in 2024-05, with the labels that each got.

#1676 Adiciona paginação ao endpoint GET /users
  models/content.js
  models/controller.js
  models/pagination.js
  models/user.js
  pages/api/v1/users/index.public.js
  tests/integration/api/v1/contents/[username]/get.test.js
  tests/integration/api/v1/contents/get.test.js
  tests/integration/api/v1/contents/rss/get.test.js
  tests/integration/api/v1/users/get.test.js
Labels: back, novo recurso

#1689 Refatoração dos testes para diminuir boilerplate (criação, ativação e features de usuário, e fetch)
  tests/integration/api/v1/contents/[username]/[slug]/patch.test.js
  tests/integration/api/v1/contents/get.test.js
  tests/integration/api/v1/contents/post.test.js
  tests/integration/api/v1/contents/rss/get.test.js
  tests/request-builder.js
Labels: testes, refatoração

#1691 Melhorando experiência do usuário nos formulários
  pages/cadastro/index.public.js
  pages/perfil/index.public.js
Labels: front

#1705 Refatoração da validação da presença do título nos conteúdos
  pages/api/v1/contents/index.public.js
  tests/integration/api/v1/contents/post.test.js
Labels: refatoração

#1706 Corrige typo em `content` (`contend`)
  models/notification.js
Labels: refatoração
