Repository filipedeschamps/tabnews.com.br, pull requests merged in 2024-07, with the labels that each got.

#1735 Corrige parâmetros de paginação para serem dinâmicos e incluir `with_root` e `with_children` em `GET /contents`
  models/controller.js
  models/pagination.js
  pages/api/v1/contents/[username]/index.public.js
  pages/api/v1/contents/index.public.js
  pages/api/v1/users/index.public.js
  tests/integration/api/v1/contents/[username]/get.test.js
  tests/integration/api/v1/contents/get.test.js
Labels: back, bug

#1741 feat(firewall emails): send emails to users affected by firewall
  infra/migrations/1713103898124_alter-table-contents-add-firewall-status.js
  infra/migrations/1715808011643_create-firewall-side-effect-functions.js
  infra/stored-procedures/firewall-create-content-text-child.pgsql
  infra/stored-procedures/firewall-create-content-text-root.pgsql
  infra/stored-procedures/firewall-create-user.pgsql
  models/content.js
  models/firewall.js
  models/notification.js
  models/transactional/emails/firewall.js
  models/transactional/index.js
  models/validator.js
  tests/integration/api/v1/contents/[username]/[slug]/patch.test.js
  tests/integration/api/v1/contents/firewall.post.test.js
  tests/integration/api/v1/contents/post.test.js
  tests/integration/api/v1/users/firewall.post.test.js
  tests/integration/models/event.test.js
  tests/orchestrator.js
  tests/unit/models/transactional/__snapshots__/index.test.js.snap
  tests/unit/models/transactional/index.test.js
Labels: back, novo recurso

#1730 Altera comportamento e mensagem de erro quando o e-mail já está cadastrado
  models/authorization.js
  pages/api/v1/recovery/index.public.js
  pages/api/v1/users/[username]/index.public.js
  pages/api/v1/users/index.public.js
  pages/cadastro/confirmar/index.public.js
  pages/cadastro/recuperar/confirmar/index.public.js
  pages/cadastro/recuperar/index.public.js
  pages/perfil/index.public.js
  tests/integration/api/v1/email-confirmation/patch.test.js
  tests/integration/api/v1/recovery/post.test.js
  tests/integration/api/v1/users/[username]/patch.test.js
  tests/integration/api/v1/users/post.test.js
Labels: front, back, segurança

#1744 Identifica uma publicação patrocinada na página dela (URL `/[username]/[slug]`)
  pages/interface/components/Content/index.js
Labels: front, novo recurso

#1746 Exibe publicação patrocinada (anúncio) no topo da lista de conteúdos
  pages/index.public.js
  pages/interface/components/ContentList/index.js
  pages/interface/components/TabNewsUI/icons/index.js
  pages/interface/index.js
  pages/interface/utils/url.js
  pages/pagina/[page]/index.public.js
  pages/recentes/comentarios/[page]/index.public.js
  pages/recentes/pagina/[page]/index.public.js
  pages/recentes/todos/[page]/index.public.js
  tests/unit/interface/utils/url.test.js
Labels: front, novo recurso

#1747 Ajusta UI para criar uma publicação patrocinada
  pages/[username]/[slug]/index.public.js
  pages/faq/index.public.js
  pages/interface/components/AdBanner/index.js
  pages/interface/components/Content/index.js
  pages/interface/components/ContentList/index.js
  pages/interface/components/TabNewsUI/index.js
Labels: front, novo recurso

#1752 Identifica publicações patrocinadas na lista de conteúdos
  pages/interface/components/ContentList/index.js
Labels: front, novo recurso

#1753 Corrige espaço em branco na lateral da página de conteúdo causado pelo banner de anúncio
  pages/[username]/[slug]/index.public.js
Labels: front, bug

#1759 Clarifica no FAQ o que acontece quando o orçamento do anúncio acaba
  pages/faq/index.public.js
Labels: front

#1766 Adiciona testes que garantem que os anúncios não influenciam no prestígio dos usuários
  .eslintrc
  tests/integration/api/v1/_use-cases/registration-flow.test.js
  tests/integration/api/v1/activation/patch.test.js
  tests/integration/api/v1/contents/[username]/[slug]/children/get.test.js
  tests/integration/api/v1/contents/[username]/[slug]/get.test.js
  tests/integration/api/v1/contents/[username]/[slug]/parent/get.test.js
  tests/integration/api/v1/contents/[username]/[slug]/patch.test.js
  tests/integration/api/v1/contents/[username]/[slug]/root/get.test.js
  tests/integration/api/v1/contents/[username]/[slug]/tabcoins/post.test.js
  tests/integration/api/v1/contents/[username]/[slug]/thumbnail/get.test.js
  tests/integration/api/v1/contents/[username]/get.test.js
  tests/integration/api/v1/contents/firewall.post.test.js
  tests/integration/api/v1/contents/get.test.js
  tests/integration/api/v1/contents/post.test.js
  tests/integration/api/v1/contents/rss/get.test.js
  tests/integration/api/v1/email-confirmation/patch.test.js
  tests/integration/api/v1/migrations/get.test.js
  tests/integration/api/v1/migrations/post.test.js
  tests/integration/api/v1/recovery/patch.test.js
  tests/integration/api/v1/recovery/post.test.js
  tests/integration/api/v1/sessions/delete.test.js
  tests/integration/api/v1/sessions/get.test.js
  tests/integration/api/v1/sessions/post.test.js
  tests/integration/api/v1/sponsored-beta/get.test.js
  tests/integration/api/v1/status/get.test.js
  tests/integration/api/v1/status/votes/get.test.js
  tests/integration/api/v1/swr/get.test.js
  tests/integration/api/v1/user/get.test.js
  tests/integration/api/v1/user/post.test.js
  tests/integration/api/v1/users/[username]/delete.test.js
  tests/integration/api/v1/users/[username]/get.test.js
  tests/integration/api/v1/users/[username]/patch.test.js
  tests/integration/api/v1/users/firewall.post.test.js
  tests/integration/api/v1/users/get.test.js
  tests/integration/api/v1/users/post.test.js
  tests/integration/infra/under-maintenance.test.js
  tests/integration/models/event.test.js
  tests/unit/infra/under-maintenance.test.js
  tests/unit/interface/utils/error-message.test.js
Labels: testes

#1765 Cria endpoint para obter dados relacionados à um evento do firewall interno
  models/authorization.js
  models/event.js
  models/firewall/event-types.js
  models/firewall/find.js
  models/firewall/index.js
  models/firewall/rules.js
  models/reward.js
  models/user-features.js
  models/user.js
  models/validator.js
  pages/api/v1/contents/[username]/[slug]/index.public.js
  pages/api/v1/contents/[username]/[slug]/tabcoins/index.public.js
  pages/api/v1/contents/index.public.js
  pages/api/v1/events/firewall/[id]/index.public.js
  pages/api/v1/users/[username]/index.public.js
  pages/api/v1/users/index.public.js
  tests/integration/api/v1/events/firewall/[id]/get.test.js
  tests/orchestrator.js
  tests/unit/models/reward.test.js
Labels: back, novo recurso

#1737 Diminui idas ao banco de dados na edição de usuários e na validação do token de confirmação do e-mail
  models/balance.js
  models/email-confirmation.js
  models/recovery.js
  models/user.js
  pages/api/v1/users/[username]/index.public.js
  tests/integration/api/v1/email-confirmation/patch.test.js
  tests/integration/api/v1/users/[username]/patch.test.js
  tests/orchestrator.js
Labels: back, refatoração
