Repository filipedeschamps/tabnews.com.br, pull requests merged in 2024-01, with the labels that each got.

#1590 fix: texto TabCoin no singular concatena com valor booleano
  pages/interface/components/TabCoinCount/index.js
Labels: front, bug

#1582 Criar página sobre a evolução do TabNews (da concepção ao lançamento) no museu
  pages/museu/evolucao-do-tabnews/index.public.js
  pages/museu/index.public.js
Labels: front, novo recurso

#1580 Usando tags mais adequadas para acessibilidade e SEO
  pages/interface/components/Content/index.js
  pages/interface/components/ContentList/index.js
  pages/interface/components/DefaultLayout/index.js
  pages/interface/components/Header/index.js
  pages/interface/components/ReadTime/index.js
  pages/interface/components/TabCashCount/index.js
  pages/interface/components/TabCoinCount/index.js
  pages/pagina/[page]/index.public.js
  pages/perfil/index.public.js
Labels: front, acessibilidade, SEO

#1595 Corrige a navegação por teclas no menu do header
  pages/interface/components/ContentList/index.js
  pages/interface/components/Header/index.js
  pages/interface/components/SearchBox/index.js
  pages/interface/components/ThemeSelector/index.js
  pages/interface/hooks/useMediaQuery/index.js
Labels: front, bug, acessibilidade

#1593 Expõe novas listas de conteúdos recentes (comentários e todos)
  next.config.js
  pages/index.public.js
  pages/interface/components/ContentList/index.js
  pages/interface/components/Head/index.js
  pages/interface/components/Header/index.js
  pages/interface/components/RecentTabNav/index.js
  pages/interface/components/TabNewsUI/index.js
  pages/pagina/[page]/index.public.js
  pages/recentes/comentarios/[page]/index.public.js
  pages/recentes/index.public.js
  pages/recentes/pagina/[page]/index.public.js
  pages/recentes/todos/[page]/index.public.js
Labels: front, back, novo recurso

#1589 Identificar o autor da publicação principal da página nos comentários
  pages/[username]/[slug]/index.public.js
  pages/interface/components/Content/index.js
  pages/interface/components/ReadTime/index.js
  pages/interface/components/TabNewsUI/index.js
  pages/interface/components/Tooltip/index.js
Labels: front, novo recurso

#1581 Criar página para o FAQ
  pages/faq/index.public.js
  pages/interface/components/Footer/index.js
Labels: front, novo recurso

#1602 Usar variáveis de ambiente no docker-compose.development.yml
  .github/workflows/ci.yml
  infra/docker-compose.development.yml
  package.json
Labels: infra, bug

#1603 Adicionar rel="nofollow" nos links de conteúdos gerados por usuário
  package-lock.json
  package.json
  pages/faq/index.public.js
  pages/interface/components/Content/index.js
  pages/interface/components/Markdown/index.js
  pages/interface/components/Markdown/plugins/external-links.js
  pages/interface/index.js
  pages/interface/utils/trusted-domain.js
  pages/museu/evolucao-do-tabnews/index.public.js
  pages/termos-de-uso/index.public.js
  tests/unit/interface/utils/trusted-domain.test.js
Labels: front, novo recurso, SEO

#1604 Exibir sugestão randômica de título no placeholder ao criar conteúdo
  pages/interface/components/Content/index.js
Labels: front, novo recurso

#1583 Criar o CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
  pages/faq/index.public.js
Labels: documentação

#1605 Responder "O que é o TabNews" no FAQ (e outras melhorias)
  README.md
  pages/faq/index.public.js
Labels: front

#1601 feat: adicionar retorno de resultados para comentários
  models/content.js
  pages/api/v1/contents/index.public.js
  tests/integration/api/v1/contents/get.test.js
Labels: back

#1613 Adiciona Turnstile para executar os desafios da Cloudflare sempre que for necessário
  .env
  pages/_app.public.js
  pages/interface/components/TabNewsUI/index.js
  pages/interface/components/Turnstile/index.js
  pages/interface/hooks/useUser/index.js
Labels: front, novo recurso, bug
