Repository filipedeschamps/tabnews.com.br, pull requests merged in 2024-04, with the labels that each got.

#1663 feat(error message text): add `createErrorMessage` function
  pages/[username]/index.public.js
  pages/cadastro/ativar/[token].public.js
  pages/cadastro/index.public.js
  pages/cadastro/recuperar/[token].public.js
  pages/cadastro/recuperar/index.public.js
  pages/interface/components/Content/index.js
  pages/interface/components/TabCoinButtons/index.js
  pages/interface/index.js
  pages/interface/utils/error-message.js
  pages/login/index.public.js
  pages/perfil/confirmar-email/[token].public.js
  pages/perfil/index.public.js
  tests/unit/interface/utils/error-message.test.js
Labels: front

#1662 Permitir desabilitar rotas temporariamente pela variável de ambiente `UNDER_MAINTENANCE`
  .env
  infra/under-maintenance.js
  middleware.public.js
  tests/integration/infra/under-maintenance.test.js
  tests/unit/infra/under-maintenance.test.js
Labels: back, novo recurso

#1656 Migração para criar novas tabelas de saldo
  infra/migrations/1711833444337_create-separate-balance-operations-tables.js
Labels: back, refatoração

#1661 Salvar operações de saldo em `balance_operations` e nas novas tabelas e reabilitar endpoints
  infra/migrations/1712454019816_alter-function-content-credit-debit.js
  models/balance.js
  models/ban.js
  models/user.js
  queries/prestigeQueries.js
Labels: back, refatoração

#1668 Cria componente de paginação e teste de unidade no frontend
  package-lock.json
  package.json
  pages/interface/components/ContentList/index.js
  pages/interface/components/Pagination/index.js
  pages/interface/components/TabNewsUI/index.js
  tests/setup.js
  tests/unit/interface/components/Pagination/index.test.js
  vitest.config.mjs
Labels: front, testes, refatoração

#1678 Corrige o código de status da resposta da API para o método `OPTIONS` de `404` para `200`
  errors/index.js
  models/controller.js
  package-lock.json
  tests/integration/api/v1/contents/options.test.js
  tests/integration/api/v1/sessions/get.test.js
  tests/integration/api/v1/user/post.test.js
Labels: back, bug

#1673 Remove a tabela `balance_operations`
  infra/migrations/1712744727715_drop-balance-operations.js
Labels: back, refatoração

#1685 Refatora `validator` e corrige validação de `null` caso o campo seja obrigatório
  models/validator.js
  tests/integration/api/v1/activation/patch.test.js
  tests/integration/api/v1/contents/[username]/[slug]/patch.test.js
  tests/integration/api/v1/contents/get.test.js
  tests/integration/api/v1/contents/post.test.js
  tests/integration/api/v1/email-confirmation/patch.test.js
  tests/integration/api/v1/recovery/patch.test.js
  tests/integration/api/v1/recovery/post.test.js
  tests/integration/api/v1/sessions/post.test.js
  tests/integration/api/v1/users/[username]/patch.test.js
  tests/integration/api/v1/users/post.test.js
Labels: back, bug, refatoração
