Repository filipedeschamps/tabnews.com.br, pull requests merged in 2024-02, with the labels that each got.

#1620 Torna visível o Tooltip do ícone de exibir/ocultar a senha
  pages/cadastro/index.public.js
  pages/cadastro/recuperar/index.public.js
  pages/interface/components/PasswordInput/index.js
  pages/login/index.public.js
  pages/perfil/index.public.js
Labels: front, bug

#1615 Editar o perfil de outro usuário
  infra/scripts/seed-database.js
  models/authorization.js
  models/email-confirmation.js
  models/user.js
  models/validator.js
  pages/[username]/index.public.js
  pages/api/v1/users/[username]/index.public.js
  pages/perfil/index.public.js
  tests/integration/api/v1/users/[username]/patch.test.js
Labels: front, back, novo recurso, bug

#1606 React-email e componentização de emails
  CONTRIBUTING.md
  infra/email.js
  models/activation.js
  models/email-confirmation.js
  models/notification.js
  models/recovery.js
  models/transactional/components/default-layout.js
  models/transactional/emails/activation.js
  models/transactional/emails/confirmation.js
  models/transactional/emails/notification.js
  models/transactional/emails/recovery.js
  models/transactional/index.js
  package-lock.json
  package.json
  tests/integration/api/v1/_use-cases/registration-flow.test.js
  tests/integration/api/v1/contents/post.test.js
  tests/integration/api/v1/email-confirmation/patch.test.js
  tests/integration/api/v1/recovery/post.test.js
  tests/integration/api/v1/users/[username]/patch.test.js
  tests/orchestrator.js
  tests/unit/models/transactional/__snapshots__/index.test.js.snap
  tests/unit/models/transactional/index.test.js
Labels: back, novo recurso

#1625 Orientações sobre um conteúdo de mais qualidade no FAQ
  pages/faq/index.public.js
Labels: front

#1607 Exibir (e retornar via API) a quantidade de qualificações positivas e negativas do conteúdo
  models/authorization.js
  models/balance.js
  models/content.js
  models/validator.js
  pages/interface/components/ContentList/index.js
  pages/interface/components/TabCoinBalanceTooltip/index.js
  pages/interface/components/TabCoinButtons/index.js
  pages/interface/components/TabNewsUI/index.js
  queries/rankingQueries.js
  tests/integration/api/v1/contents/[username]/[slug]/children/get.test.js
  tests/integration/api/v1/contents/[username]/[slug]/get.test.js
  tests/integration/api/v1/contents/[username]/[slug]/parent/get.test.js
  tests/integration/api/v1/contents/[username]/[slug]/patch.test.js
  tests/integration/api/v1/contents/[username]/[slug]/root/get.test.js
  tests/integration/api/v1/contents/[username]/[slug]/tabcoins/post.test.js
  tests/integration/api/v1/contents/[username]/get.test.js
  tests/integration/api/v1/contents/get.test.js
  tests/integration/api/v1/contents/post.test.js
Labels: front, back, novo recurso

#1629 Atualizar regras de lint e corrigir problemas apontados pelo DeepScan
  .eslintrc
  CONTRIBUTING.md
  infra/logger.js
  infra/migrator.js
  infra/scripts/wait-for-db-connection-ready.js
  models/authentication.js
  models/content.js
  models/recovery.js
  models/remove-markdown.js
  models/validator.js
  package-lock.json
  package.json
  pages/api/v1/contents/[username]/[slug]/parent/index.public.js
  pages/api/v1/contents/[username]/[slug]/root/index.public.js
  pages/interface/components/Content/index.js
  pages/interface/components/ContentList/index.js
  tests/integration/api/v1/contents/[username]/[slug]/children/get.test.js
  tests/integration/api/v1/contents/[username]/[slug]/patch.test.js
  tests/integration/api/v1/contents/[username]/[slug]/tabcoins/post.test.js
  tests/integration/api/v1/contents/post.test.js
  tests/integration/api/v1/contents/rss/get.test.js
  tests/integration/api/v1/migrations/get.test.js
  tests/integration/api/v1/users/firewall.post.test.js
  tests/orchestrator.js
Labels: bug, testes

#1632 Melhorias envolvendo envio de emails
  infra/email.js
  models/controller.js
  pages/api/v1/contents/index.public.js
  pages/interface/components/Content/index.js
  pages/interface/index.js
  pages/interface/utils/is-valid-json-string.js
  pages/interface/utils/nd-json-stream.js
  tests/integration/api/v1/contents/post.test.js
  tests/unit/infra/email.test.js
Labels: front, back, infra, bug
