Repository filipedeschamps/tabnews.com.br, pull requests merged in 2024-06, with the labels that each got.

#1708 Usar `RequestBuilder` em mais testes de conteúdos
  tests/integration/api/v1/contents/[username]/[slug]/children/get.test.js
  tests/integration/api/v1/contents/[username]/[slug]/get.test.js
  tests/integration/api/v1/contents/[username]/[slug]/parent/get.test.js
  tests/integration/api/v1/contents/[username]/[slug]/root/get.test.js
  tests/integration/api/v1/contents/[username]/[slug]/tabcoins/post.test.js
  tests/integration/api/v1/contents/[username]/[slug]/thumbnail/get.test.js
  tests/integration/api/v1/contents/post.test.js
  tests/integration/api/v1/contents/rss/get.test.js
  tests/request-builder.js
Labels: testes, refatoração

#1725 Usa o módulo `crypto` para gerar UUIDs e move o `uuid` para `devDependencies`
  errors/index.js
  models/content.js
  models/controller.js
  package-lock.json
  package.json
  pages/api/v1/_responses/rate-limit-reached-sessions.public.js
  tests/integration/api/v1/status/votes/get.test.js
  tests/unit/models/prestige.test.js
  tests/unit/models/reward.test.js
Labels: back, refatoração

#1726 Remove propriedade obsoleta `version` do Docker Compose
  README.md
  infra/docker-compose.development.yml
Labels: infra

#1728 Remove validação de existência do `parent_id` ao modificar um conteúdo
  models/content.js
  tests/integration/api/v1/contents/post.test.js
Labels: back, bug

#1727 Salvar nos eventos o histórico de alterações de `username`
  models/event.js
  pages/api/v1/contents/[username]/[slug]/index.public.js
  pages/api/v1/users/[username]/index.public.js
  tests/integration/api/v1/contents/[username]/[slug]/patch.test.js
  tests/integration/api/v1/contents/firewall.post.test.js
  tests/integration/api/v1/events/get.test.js
  tests/integration/api/v1/users/firewall.post.test.js
  tests/integration/models/event.test.js
  tests/orchestrator.js
  tests/request-builder.js
Labels: back

#1729 Diminui idas ao banco de dados na criação e edição de conteúdos, e na edição de usuários
  models/content.js
  models/event.js
  pages/api/v1/contents/[username]/[slug]/index.public.js
  pages/api/v1/contents/index.public.js
  pages/api/v1/users/[username]/index.public.js
  tests/orchestrator.js
Labels: back, refatoração

#1736 Permite acessar a URL usando `http://ip:porta` durante o desenvolvimento
  pages/interface/components/Head/index.js
Labels: front, bug
