Repository filipedeschamps/tabnews.com.br, pull requests merged in 2024-08, with the labels that each got.

#1771 Exibe link para o FAQ na mensagem de erro sobre não conseguir criar conteúdos por causa das avaliações
  pages/interface/components/Content/index.js
Labels: front

#1783 Exibe erro de descrição ao atualizar pelo perfil do usuário
  pages/[username]/index.public.js
Labels: front, bug

#1781 Refatora/corrige alguns testes
  tests/integration/api/v1/_use-cases/registration-flow.test.js
  tests/integration/api/v1/activation/patch.test.js
  tests/integration/api/v1/contents/[username]/[slug]/children/get.test.js
  tests/integration/api/v1/contents/[username]/[slug]/get.test.js
  tests/integration/api/v1/contents/[username]/[slug]/parent/get.test.js
  tests/integration/api/v1/contents/[username]/[slug]/patch.test.js
  tests/integration/api/v1/contents/[username]/[slug]/root/get.test.js
  tests/integration/api/v1/contents/[username]/[slug]/tabcoins/post.test.js
  tests/integration/api/v1/contents/[username]/[slug]/thumbnail/get.test.js
  tests/integration/api/v1/contents/[username]/get.test.js
  tests/integration/api/v1/contents/firewall.post.test.js
  tests/integration/api/v1/contents/get.test.js
  tests/integration/api/v1/contents/options.test.js
  tests/integration/api/v1/contents/post.test.js
  tests/integration/api/v1/contents/rss/get.test.js
  tests/integration/api/v1/email-confirmation/patch.test.js
  tests/integration/api/v1/events/firewall/[id]/get.test.js
  tests/integration/api/v1/migrations/get.test.js
  tests/integration/api/v1/migrations/post.test.js
  tests/integration/api/v1/moderations/review_firewall/[id]/post.test.js
  tests/integration/api/v1/recovery/patch.test.js
  tests/integration/api/v1/recovery/post.test.js
  tests/integration/api/v1/sessions/delete.test.js
  tests/integration/api/v1/sessions/get.test.js
  tests/integration/api/v1/sessions/post.test.js
  tests/integration/api/v1/sponsored-beta/get.test.js
  tests/integration/api/v1/status/get.test.js
  tests/integration/api/v1/status/votes/get.test.js
  tests/integration/api/v1/swr/get.test.js
  tests/integration/api/v1/user/get.test.js
  tests/integration/api/v1/user/post.test.js
  tests/integration/api/v1/users/[username]/delete.test.js
  tests/integration/api/v1/users/[username]/get.test.js
  tests/integration/api/v1/users/[username]/patch.test.js
  tests/integration/api/v1/users/get.test.js
  tests/integration/api/v1/users/post.test.js
  tests/integration/infra/under-maintenance.test.js
  tests/unit/interface/components/Pagination/index.test.js
  tests/unit/models/reward.test.js
Labels: testes

#1782 Configurações do ESLint e Prettier
  .eslintignore
  .eslintrc
  .prettierignore
  infra/scripts/seed-database.js
  infra/scripts/wait-for-db-connection-ready.js
  infra/under-maintenance.js
  middleware.public.js
  models/controller.js
  models/firewall/rules.js
  models/health.js
  models/remove-markdown.js
  next.config.js
  package-lock.json
  package.json
  pages/[username]/classificados/[page]/index.public.js
  pages/[username]/comentarios/[page]/index.public.js
  pages/[username]/conteudos/[page]/index.public.js
  pages/api/v1/contents/index.public.js
  pages/interface/components/Content/index.js
  pages/pagina/[page]/index.public.js
  pages/recentes/classificados/[page]/index.public.js
  pages/recentes/comentarios/[page]/index.public.js
  pages/recentes/pagina/[page]/index.public.js
  pages/recentes/todos/[page]/index.public.js
  tests/integration/api/v1/events/firewall/[id]/get.test.js
Labels: dependências, refatoração

#1778 Cria página para listar usuários
  package-lock.json
  package.json
  pages/[username]/index.public.js
  pages/_app.public.js
  pages/api/v1/users/index.public.js
  pages/interface/components/Header/index.js
  pages/interface/components/SkeletonLoader/index.js
  pages/interface/components/TabNewsUI/index.js
  pages/interface/components/UserList/index.js
  pages/moderacao/usuarios/[page]/index.public.js
  pages/publicar/index.public.js
  pages/status/index.public.js
  tests/integration/api/v1/users/get.test.js
Labels: front, novo recurso

#1786 Carrega anúncio após carregar a página do conteúdo para não indexá-lo
  pages/[username]/[slug]/index.public.js
  pages/interface/components/AdBanner/index.js
Labels: SEO

#1787 Atualiza as propriedades do componente `Tooltip` para serem compatíveis com a nova versão (`Tooltip v2`)
  package-lock.json
  package.json
  pages/[username]/[slug]/index.public.js
  pages/interface/components/AdBanner/index.js
  pages/interface/components/Content/index.js
  pages/interface/components/ContentList/index.js
  pages/interface/components/Header/index.js
  pages/interface/components/PastTime/index.js
  pages/interface/components/TabCashCount/index.js
  pages/interface/components/TabCoinBalanceTooltip/index.js
  pages/interface/components/TabCoinButtons/index.js
  pages/interface/components/TabCoinCount/index.js
Labels: front, dependências
